### ISSUE TITLE
프로젝트 내에서 tabTeam.stroyboard 누락 문제.

### ISSUE THREAD

**Issue by mocona** [ProjectInTheClass/bowling-E#3]
tabTeam.stroyboard 파일은 존재하는데, 프로젝트 내의 파일 등록이 누락되었네요.

어떤 사연이 있겠죠? ;) - 컴파일이 되지 않아서 알게 된 오류. ㅎㅎ

처리하세요. 요 앞의 클래스 초기화 오류를 해결하면 만나게 된답니다. :)

**Comment by n-jngwn** [comment]
해결했음
